name: build-and-push

on:
  push:
    branches:
      - main

jobs:
  build:
    strategy:
      matrix:
        include:
          - image: mlflow
            fromImage: python
            fromImageTag: 3.10-slim-bullseye
            appVersion: 1.26.1
          - image: mlflow
            fromImage: python
            fromImageTag: 3.10-slim-bullseye
            appVersion: 1.27.0
          - image: mlflow
            fromImage: python
            fromImageTag: 3.10-slim-bullseye
            appVersion: 1.28.0
          - image: mlflow
            fromImage: python
            fromImageTag: 3.10-slim-bullseye
            appVersion: 1.29.0
          - image: tellmewhattodo
            fromImage: python
            fromImageTag: 3.10-slim-bullseye
            appVersion: 2.1.1
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          file: ./${{ matrix.image }}/Dockerfile
          context: ./${{ matrix.image }}
          builder: ${{ steps.buildx.outputs.name }}
          push: true
          build-args: |
            FROM_IMAGE=${{ matrix.fromImage }}
            FROM_IMAGE_TAG=${{ matrix.fromImageTag }}
            APP_VERSION=${{ matrix.appVersion }}
          tags: |
            ${{ secrets.DOCKER_HUB_USERNAME }}/${{ matrix.image }}:${{ matrix.appVersion }}-${{ matrix.fromImageTag }}
          cache-from: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/${{ matrix.image }}:buildcache
          cache-to: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/${{ matrix.image }}:buildcache,mode=max
